### ISSUE TITLE
Floating above chairs when sitting

### ISSUE THREAD

**Issue by 123B3n** [acemod/ACEX#101] opened 2018-01-18 20:01 UTC
**Arma 3 Version:** `1.80.143869` (stable)
**CBA Version:** `3.5.0.171204` (stable)
**ACE3 Version:** `3.12.1` (stable)
**ACEX Version:** `3.3.0` (stable)

**Mods:**
```
- CBA_A3
- CUP Weapons
- ace
- CUP Units
- ACEX
- ASR AI3
- Advanced Urban Rappelling
- CUP Terrains - Core
- CUP Terrains - Maps
- CUP Vehicles
- Enhanced Movement
- FA-18 Super Hornet
- RHSAFRF
- RHSUSAF
- RHSGREF
- RHSSAF
```

**Description:**
- Sitting on chairs makes the character float above the object, not sure what the problem is. Was working just fine before but now all of the sudden it's floating above the object just like if there was an invisible wall. It happens to not just me but everyone on my server.

**Steps to reproduce:**
- Make mission, place the modules necessary for ACE to work and ACEX sitting, create a char from classname "Land_CampingChair_V2_F" and try and sit on it.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer)

**Placed Modules:**
- None

**RPT log file:**
- Not really an error per say but if u really need the RPT log just let me know and I'll go and get it.

**Comment by jonpas** [comment] 2018-01-18 20:50
Duplicate of #80 

"Enhanced Movement" is causing it, I believe they haven't released an update for this conflict yet.

**Closed by jonpas** 2018-01-18 20:50 UTC
Labels: duplicate
