### ISSUE TITLE
Sitting but floating?

### ISSUE THREAD

**Issue by DukeVenator** [acemod/ACEX#168] opened 2019-02-02 07:25 UTC
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `2.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)
**ACEX Version:** `3.x.x` (stable / dev + commit hash)
All workshop versions 
**Mods:**
```
- CBA_A3
- ace
- acex
And that's about it ^
```

**Description:**
- players that sit hover about 1 meter above chairs in a sit animation?

**Steps to reproduce:**
- Sit in a variety of chairs on MP

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Additional information:**
-

**Comment by TheMagnetar** [comment] 2019-02-02 10:03
Can you post the rpt? There was some problem with enhanced movement

**Comment by MisterHLunaticwraith** [comment] 2019-02-13 16:00
I can confirm there is still the issue with enhanced movement (it was solved for a while but has returned)

**Comment by GSGChaser** [comment] 2019-04-08 11:21
If you try to apply the old fix the pbo goes "circular addon dependency detected" and crashes the game.

**Comment by Tress16** [comment] 2019-05-04 18:47
Will this be fixed again? We would like to use both mods (Enhanced movement and ACEX) again.

**Comment by jonpas** [comment] 2019-05-04 23:25
We didn't change anything fundamentally. I don't know what Enhanced Movement was using to do compatibility, I'd gladly help if I could.

Closing this as 3rd party issue / conflict as there is nothing we can do at this time. Feel free to refer Enhanced Movement developers here or to me.

**Closed by jonpas** 2019-05-04 23:25 UTC

**Comment by jetelain** [comment] 2020-02-04 19:07
For people, like me, that didn't found the information:

It's caused by the "Forced Walkable Surface", that you can disable in "Enhanced Movement" settings.

"Enhanced Movement" tests `acex_sitting_issitting` but the property has changed in #144, and it should now tests `acex_sitting_sittingstatus`. It has to be fixed by "Enhanced Movement" developers.

You can also use this fixed version from a third party developer https://steamcommunity.com/sharedfiles/filedetails/?id=1586691629
