### ISSUE TITLE
'acex_field_rations' requires addon 'ace_interact_menu'

### ISSUE THREAD

**Issue by SouthernGoods** [acemod/ACEX#195] opened 2019-11-02 20:44 UTC
Having an issue loading acex onto my server, the issue happens whenever i try to launch the server. 
'acex_field_rations' requires addon 'ace_interact_menu'
Circular addon dependency detected, check Rpt for details.

I have copied the arma 3 server report below. 
https://pastebin.com/Ug0B7kSy

**Comment by SouthernGoods** [comment] 2019-11-02 20:44
This issue has only appeared after the A3 update this past week.

**Comment by SouthernGoods** [comment] 2019-11-02 21:13
Tried loading it with just ace, acex, and CBA. Same issue.

**Comment by dedmen** [comment] 2019-11-02 21:48
Can't reproduce.
Looking at your mods, you are loading ace twice, once normal ace, and again some weirdly modified star wars ace thing.

**Comment by SouthernGoods** [comment] 2019-11-03 01:00
Ah ok there may be an issue with the server settings in the manager i'm using. Thank you!

**Comment by SouthernGoods** [comment] 2019-11-03 01:10
Here's the pastebin with only ACE,ACEX, and CBZ. 
https://pastebin.com/kgz0e4c8

**Comment by dedmen** [comment] 2019-11-03 13:18
> how you are recognizing a weird starwars ace being loaded as well
The -mod parameter in your first log shows `501st` which is a star wars unit that I already know for having reuploaded ACE and TFAR which I already DMCA'ed in the past

That makes no sense, where did you download your ACE/ACEX from?

**Comment by SouthernGoods** [comment] 2019-11-03 23:33
STEAM Workshop, we rebuild our server from scratch and it seems to have fixed the issue. Thank you for the help.

**Comment by dedmen** [comment] 2019-11-07 09:31
If its solved then please close the ticket ;)

**Comment by mharis001** [comment] 2020-01-04 04:38
Closing since issue has been resolved.

**Closed by mharis001** 2020-01-04 04:38 UTC
Labels: question

**Comment by ejaimesd** [comment] 2020-08-04 18:46
> STEAM Workshop, we rebuild our server from scratch and it seems to have fixed the issue. Thank you for the help.

When you said rebuild from the scratch did you mean System too? or just Arma 3 Server files?
I have exactly the same error ...
